### ISSUE TITLE
OSError: [E050] Can't find model 'en_core_web_sm'. It doesn't seem to be a Python package or a valid path to a data directory.

### ISSUE THREAD

**Issue by xiangxinyue** [CMUSTRUDEL/snorkel#7]
[nltk_data] Downloading package vader_lexicon to
[nltk_data]     /home/xinyue/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!
Traceback (most recent call last):
  File "training_functions.py", line 292, in <module>
    spacy = SpacyPreprocessor(text_field="body", doc_field="doc", memoize=True)
  File "/home/xinyue/.local/lib/python3.8/site-packages/snorkel/preprocess/nlp.py", line 72, in __init__
    self._nlp = spacy.load(language, disable=disable or [])
  File "/home/xinyue/.local/lib/python3.8/site-packages/spacy/__init__.py", line 50, in load
    return util.load_model(
  File "/home/xinyue/.local/lib/python3.8/site-packages/spacy/util.py", line 331, in load_model
    raise IOError(Errors.E050.format(name=name))
OSError: [E050] Can't find model 'en_core_web_sm'. It doesn't seem to be a Python package or a valid path to a data directory.

**Comment by xiangxinyue** [comment]
try to solve the issue by following:

pip3 install https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.2.0/en_core_web_sm-2.2.0.tar.gz

**Comment by xiangxinyue** [comment]
> try to solve the issue by following:
> 
> pip3 install https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.2.0/en_core_web_sm-2.2.0.tar.gz

OSError: [E053] Could not read config.cfg from /home/xinyue/.local/lib/python3.8/site-packages/en_core_web_sm/en_core_web_sm-2.2.0/config.cfg

**Comment by xiangxinyue** [comment]
https://spacy.io/usage

**Comment by sophieball** [comment]
Is this solved? If so, I'd close this issue.

**Comment by xiangxinyue** [comment]
> Is this solved? If so, I'd close this issue.

Yes, it fixed

**Comment by xiangxinyue** [comment]
Closed, 
```
pip3 install -U spacy
spacy download en_core_web_sm
```
works
